/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file msg_question.png */
extern const unsigned char msg_question[];

/* created by reswrap from file msg_warning.png */
extern const unsigned char msg_warning[];

/* created by reswrap from file msg_error.png */
extern const unsigned char msg_error[];

/* created by reswrap from file msg_info.png */
extern const unsigned char msg_info[];

