// Laenderliste aus dsprop.dll (deutsches Windows 2000 SP4, Texte 4000 ff.):
// Anzeigename wie im Original in Grossbuchstaben, ISO-3166-Kuerzel und
// -Nummer -- fuer c, co und countryCode.
#pragma once
struct W2kCountry { const char* name; const char* alpha2; int numeric; };
static const W2kCountry W2K_COUNTRIES[] = {
	{ "AFGHANISTAN", "AF", 4 },
	{ "ALBANIEN", "AL", 8 },
	{ "ALGERIEN", "DZ", 12 },
	{ "AMERIKANISCH-SAMOA", "AS", 16 },
	{ "ANDORRA", "AD", 20 },
	{ "ANGOLA", "AO", 24 },
	{ "ANGUILLA", "AI", 660 },
	{ "ANTARKTIS", "AQ", 10 },
	{ "ANTIGUA UND BARBUDA", "AG", 28 },
	{ "ARGENTINIEN", "AR", 32 },
	{ "ARMENIEN", "AM", 51 },
	{ "ARUBA", "AW", 533 },
	{ "AUSTRALIEN", "AU", 36 },
	{ "ÖSTERREICH", "AT", 40 },
	{ "ASERBAIDSCHAN", "AZ", 31 },
	{ "BAHAMAS", "BS", 44 },
	{ "BAHRAIN", "BH", 48 },
	{ "BANGLADESCH", "BD", 50 },
	{ "BARBADOS", "BB", 52 },
	{ "BELARUS", "BY", 112 },
	{ "BELGIEN", "BE", 56 },
	{ "BELIZE", "BZ", 84 },
	{ "BENIN", "BJ", 204 },
	{ "BERMUDA", "BM", 60 },
	{ "BHUTAN", "BT", 64 },
	{ "BOLIVIEN", "BO", 68 },
	{ "BOSNIEN AND HERZEGOWINA", "BA", 70 },
	{ "BOTSWANA", "BW", 72 },
	{ "BOUVET INSEL", "BV", 74 },
	{ "BRASILIEN", "BR", 76 },
	{ "BRITISCHES TERRITORIUM IM INDISCHEN OZEAN", "IO", 86 },
	{ "BRUNEI DARUSSALAM", "BN", 96 },
	{ "BULGARIEN", "BG", 100 },
	{ "BURKINA FASO", "BF", 854 },
	{ "BURUNDI", "BI", 108 },
	{ "KAMBODSCHA", "KH", 116 },
	{ "KAMERUN", "CM", 120 },
	{ "KANADA", "CA", 124 },
	{ "KAP VERDE", "CV", 132 },
	{ "CAYMAN-INSELN", "KY", 136 },
	{ "ZENTRALAFRIKANISCHE REPUBLIK", "CF", 140 },
	{ "TSCHAD", "TD", 148 },
	{ "CHILE", "CL", 152 },
	{ "CHINA", "CN", 156 },
	{ "WEIHNACHTSINSEL", "CX", 162 },
	{ "COCOS-KEELING-INSELN", "CC", 166 },
	{ "KOLUMBIEN", "CO", 170 },
	{ "KOMOREN", "KM", 174 },
	{ "KONGO", "CG", 178 },
	{ "DEMOKRATISCHE REPUBLIK KONGO", "CD", 180 },
	{ "COOK INSELN", "CK", 184 },
	{ "COSTA RICA", "CR", 188 },
	{ "KROATIEN (kroatisch: Hrvatska)", "HR", 191 },
	{ "KUBA", "CU", 192 },
	{ "ZYPERN", "CY", 196 },
	{ "TSCHECHISCHE REPUBLIK", "CZ", 203 },
	{ "DÄNEMARK", "DK", 208 },
	{ "DSCHIBUTI", "DJ", 262 },
	{ "DOMINICA", "DM", 212 },
	{ "DOMINIKANISCHE REPUBLIK", "DO", 214 },
	{ "OSTTIMOR", "TP", 626 },
	{ "ECUADOR", "EC", 218 },
	{ "ÄGYPTEN", "EG", 818 },
	{ "EL SALVADOR", "SV", 222 },
	{ "ÄQUATORIALGUINEA", "GQ", 226 },
	{ "ERITREA", "ER", 232 },
	{ "ESTLAND", "EE", 233 },
	{ "ÄTHIOPIEN", "ET", 231 },
	{ "MALWINEN", "FK", 238 },
	{ "FÄRÖER INSELN", "FO", 234 },
	{ "FIDSCHI", "FJ", 242 },
	{ "FINNLAND", "FI", 246 },
	{ "FRANKREICH", "FR", 250 },
	{ "FRANKREICH, METROPOLITAN", "FX", 249 },
	{ "FRANZÖSISCH GUYANA", "GF", 254 },
	{ "FRANZÖSISCH POLYNESIEN", "PF", 258 },
	{ "FRANZÖSISCHE SÜDGEBIETE", "TF", 260 },
	{ "GABUN", "GA", 266 },
	{ "GAMBIA", "GM", 270 },
	{ "GEORGIEN", "GE", 268 },
	{ "DEUTSCHLAND", "DE", 276 },
	{ "GHANA", "GH", 288 },
	{ "GIBRALTAR", "GI", 292 },
	{ "GRIECHENLAND", "GR", 300 },
	{ "GRÖNLAND", "GL", 304 },
	{ "GRENADA", "GD", 308 },
	{ "GUADELOUPE", "GP", 312 },
	{ "GUAM", "GU", 316 },
	{ "GUATEMALA", "GT", 320 },
	{ "GUINEA", "GN", 324 },
	{ "GUINEA-BISSAU", "GW", 624 },
	{ "GUYANA", "GY", 328 },
	{ "HAITI", "HT", 332 },
	{ "HEARD- UND MC DONALD-INSELN", "HM", 334 },
	{ "VATIKANSTADT", "VA", 336 },
	{ "HONDURAS", "HN", 340 },
	{ "HONGKONG S.A.R. (CHINA)", "HK", 344 },
	{ "UNGARN", "HU", 348 },
	{ "ISLAND", "IS", 352 },
	{ "INDIEN", "IN", 356 },
	{ "INDONESIEN", "ID", 360 },
	{ "IRAN (ISLAMISCHE REPUBLIK)", "IR", 364 },
	{ "IRAK", "IQ", 368 },
	{ "IRLAND", "IE", 372 },
	{ "ISRAEL", "IL", 376 },
	{ "ITALIEN", "IT", 380 },
	{ "JAMAIKA", "JM", 388 },
	{ "JAPAN", "JP", 392 },
	{ "JORDAN", "JO", 400 },
	{ "KASACHSTAN", "KZ", 398 },
	{ "KENIA", "KE", 404 },
	{ "KIRIBATI", "KI", 296 },
	{ "NORDKOREA", "KP", 408 },
	{ "SÜDKOREA", "KR", 410 },
	{ "KUWAIT", "KW", 414 },
	{ "KIRGISTAN", "KG", 417 },
	{ "LAOS", "LA", 418 },
	{ "LETTLAND", "LV", 428 },
	{ "LIBANON", "LB", 422 },
	{ "LESOTHO", "LS", 426 },
	{ "LIBERIA", "LR", 430 },
	{ "LIBYEN", "LY", 434 },
	{ "LIECHTENSTEIN", "LI", 438 },
	{ "LITAUEN", "LT", 440 },
	{ "LUXEMBURG", "LU", 442 },
	{ "MACAO S.A.R. (CHINA)", "MO", 446 },
	{ "MAZEDONIEN, EHEM. JUGOSLAWISCHE REP.", "MK", 807 },
	{ "MADAGASKAR", "MG", 450 },
	{ "MALAWI", "MW", 454 },
	{ "MALAYSIA", "MY", 458 },
	{ "MALEDIVEN", "MV", 462 },
	{ "MALI", "ML", 466 },
	{ "MALTA", "MT", 470 },
	{ "MARSHALL-INSELN", "MH", 584 },
	{ "MARTINIQUE", "MQ", 474 },
	{ "MAURETANIEN", "MR", 478 },
	{ "MAURITIUS", "MU", 480 },
	{ "MAYOTTE-INSEL", "YT", 175 },
	{ "MEXICO", "MX", 484 },
	{ "MICRONESIEN", "FM", 583 },
	{ "MOLDAWIEN", "MD", 498 },
	{ "MONACO", "MC", 492 },
	{ "MONGOLEI", "MN", 496 },
	{ "MONTSERRAT", "MS", 500 },
	{ "MAROKKO", "MA", 504 },
	{ "MOSAMBIK", "MZ", 508 },
	{ "MYANMAR", "MM", 104 },
	{ "NAMIBIA", "NA", 516 },
	{ "NAURU", "NR", 520 },
	{ "NEPAL", "NP", 524 },
	{ "NIEDERLANDE", "NL", 528 },
	{ "NIEDERLÄNDISCHE ANTILLEN", "AN", 530 },
	{ "NEUKALEDONIEN", "NC", 540 },
	{ "NEUSEELAND", "NZ", 554 },
	{ "NICARAGUA", "NI", 558 },
	{ "NIGER", "NE", 562 },
	{ "NIGERIA", "NG", 566 },
	{ "NIUE", "NU", 570 },
	{ "NORFOLK-INSEL", "NF", 574 },
	{ "NÖRDLICHE MARIANEN", "MP", 580 },
	{ "NORWEGEN", "NO", 578 },
	{ "OMAN", "OM", 512 },
	{ "PAKISTAN", "PK", 586 },
	{ "PALAU", "PW", 585 },
	{ "PANAMA", "PA", 591 },
	{ "PAPUA-NEUGUINEA", "PG", 598 },
	{ "PARAGUAY", "PY", 600 },
	{ "PERU", "PE", 604 },
	{ "PHILIPPINEN", "PH", 608 },
	{ "PITCAIRN", "PN", 612 },
	{ "POLEN", "PL", 616 },
	{ "PORTUGAL", "PT", 620 },
	{ "PUERTO RICO", "PR", 630 },
	{ "KATAR", "QA", 634 },
	{ "REUNION-INSEL", "RE", 638 },
	{ "RUMÄNIEN", "RO", 642 },
	{ "RUSSISCHE  FÖDERATION", "RU", 643 },
	{ "RUANDA", "RW", 646 },
	{ "SAINT KITTS UND NEVIS", "KN", 659 },
	{ "SAINT LUCIA", "LC", 662 },
	{ "SAINT VINCENT UND DIE GRENADINEN", "VC", 670 },
	{ "SAMOA", "WS", 882 },
	{ "SAN MARINO", "SM", 674 },
	{ "SAO TOME AND PRINCIPE", "ST", 678 },
	{ "SAUDI ARABIEN", "SA", 682 },
	{ "SENEGAL", "SN", 686 },
	{ "SEYCHELLEN", "SC", 690 },
	{ "SIERRA LEONE", "SL", 694 },
	{ "SINGAPUR", "SG", 702 },
	{ "SLOWAKEI (Slowakische Republik)", "SK", 703 },
	{ "SLOWENIEN", "SI", 705 },
	{ "SOLOMON INSELN", "SB", 90 },
	{ "SOMALIA", "SO", 706 },
	{ "SÜDAFRICA", "ZA", 710 },
	{ "SÜDGEORGIEN UND SANDWICH-INSELN", "GS", 239 },
	{ "SPANIEN", "ES", 724 },
	{ "SRI LANKA", "LK", 144 },
	{ "ST. HELENA", "SH", 654 },
	{ "ST. PIERRE UND MIQUELON", "PM", 666 },
	{ "SUDAN", "SD", 736 },
	{ "SURINAM", "SR", 740 },
	{ "SVALBARD UND JAN-MAYEN-INSELN", "SJ", 744 },
	{ "SWASILAND", "SZ", 748 },
	{ "SCHWEDEN", "SE", 752 },
	{ "SCHWEIZ", "CH", 756 },
	{ "SYRIEN", "SY", 760 },
	{ "TAIWAN", "TW", 158 },
	{ "TADSCHIKISTAN", "TJ", 762 },
	{ "TANSANIA", "TZ", 834 },
	{ "THAILAND", "TH", 764 },
	{ "TOGO", "TG", 768 },
	{ "TOKELAU", "TK", 772 },
	{ "TONGA", "TO", 776 },
	{ "TRINIDAD UND TOBAGO", "TT", 780 },
	{ "TUNESIEN", "TN", 788 },
	{ "TÜRKEI", "TR", 792 },
	{ "TURKMENISTAN", "TM", 795 },
	{ "TURKS- UND CAICOS-INSELN", "TC", 796 },
	{ "TUWALU", "TV", 798 },
	{ "UGANDA", "UG", 800 },
	{ "UKRAINE", "UA", 804 },
	{ "VEREINIGTE ARABISCHE EMIRATE", "AE", 784 },
	{ "GROSSBRITANNIEN", "GB", 826 },
	{ "VEREINIGTE STAATEN", "US", 840 },
	{ "USA, KLEINERE AUSGELAGERTE INSELN", "UM", 581 },
	{ "URUGUAY", "UY", 858 },
	{ "USBEKISTAN", "UZ", 860 },
	{ "VANUATU", "VU", 548 },
	{ "VENEZUELA", "VE", 862 },
	{ "VIETNAM", "VN", 704 },
	{ "BRITISCHE JUNGFERN-INSELN", "VG", 92 },
	{ "AMERIKANISCHE JUNGFERN-INSELN", "VI", 850 },
	{ "WALLIS- UND FUTUNA-INSELN", "WF", 876 },
	{ "WESTSAHARA", "EH", 732 },
	{ "JEMEN", "YE", 887 },
	{ "JUGOSLAWIEN", "YU", 891 },
	{ "SAMBIA", "ZM", 894 },
	{ "SIMBABWE", "ZW", 716 },
};
