/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file evt_error_orig.png */
extern const unsigned char evticon_error[];

/* created by reswrap from file evt_warning_orig.png */
extern const unsigned char evticon_warning[];

/* created by reswrap from file evt_info_orig.png */
extern const unsigned char evticon_info[];

