/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file eventvwr/res/icons/evt_error.png */
extern const unsigned char evticon_error[];

/* created by reswrap from file eventvwr/res/icons/evt_warning.png */
extern const unsigned char evticon_warning[];

/* created by reswrap from file eventvwr/res/icons/evt_info.png */
extern const unsigned char evticon_info[];

